# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a Node.js version that is compatible with the runner

      - name: Install dependencies
        working-directory: ./website
        run: npm install

      - name: Run build
        working-directory: ./website
        run: npm run build

      - name: Push to Github Pages branch
        run: |
          cd website/build/tech-portfolio
          touch .nojekyll
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} INPUT_DIRECTORY=$(pwd) publish.sh
